# Generated by Django 5.2.3 on 2025-06-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('shipping_address', models.TextField()),
                ('total_amount', models.FloatField()),
                ('shipping_speed', models.CharField(choices=[('standard', 'Standard (4-7 days)'), ('express', 'Express (2-3 days)'), ('fast', 'Fast (Next Day)')], default='standard', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awb_number', models.CharField(blank=True, max_length=50, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
