# Generated by Django 5.2.3 on 2025-07-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='shipping_category',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='size',
        ),
        migrations.AddField(
            model_name='accessory',
            name='shipment_length',
            field=models.FloatField(default=0.0),
        ),
    ]
