# Generated by Django 5.2.3 on 2025-07-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_accessory_shipping_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='is_COD',
            field=models.BooleanField(default=True, verbose_name='Cash on Delivery Available'),
        ),
    ]
