# Generated by Django 5.2.3 on 2025-06-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_accessory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='is_universal',
            field=models.BooleanField(default=False),
        ),
    ]
