# Generated by Django 5.2.3 on 2025-07-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_accessory_is_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='subimage1',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/subimages/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='subimage2',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/subimages/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='subimage3',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/subimages/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='subimage4',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/subimages/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='subimage5',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/subimages/'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='bike_models',
            field=models.ManyToManyField(blank=True, related_name='accessories', to='products.bikemodel'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='accessories', to='products.category'),
        ),
    ]
