# Generated by Django 5.2.3 on 2025-06-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_pickuplocation_shippingaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='PickupLocation',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
