# Generated by Django 5.2.3 on 2025-06-26 09:00

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_order_shipping_address_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='accessories/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
    ]
