# Generated by Django 5.2.3 on 2025-06-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_accessory_image_alter_blog_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='accessory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
