# Generated by Django 5.2.3 on 2025-06-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_accessory_image_url_remove_category_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='accessory',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
