# Generated by Django 5.2.3 on 2025-06-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_accessory_image_remove_blog_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(help_text='Hex code, e.g. #ff0000', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='price',
        ),
        migrations.AddField(
            model_name='accessory',
            name='bike_brands',
            field=models.ManyToManyField(blank=True, related_name='accessories', to='products.bikebrand'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='MRP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessory',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Offer Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessory',
            name='shipping_category',
            field=models.CharField(blank=True, choices=[('1kg', '1kg'), ('2kg', '2kg'), ('3kg', '3kg'), ('4kg', '4kg'), ('5kg', '5kg')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='categories',
        ),
        migrations.AddField(
            model_name='accessory',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='accessories', to='products.color'),
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_at', models.DateTimeField(auto_now_add=True)),
                ('accessories', models.ManyToManyField(related_name='featured_in', to='products.accessory')),
            ],
        ),
        migrations.AddField(
            model_name='accessory',
            name='categories',
            field=models.ManyToManyField(related_name='accessories', to='products.category'),
        ),
    ]
